CREATE USER 'admin'@'%' IDENTIFIED WITH mysql_native_password AS '***';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0,
      MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `admin`;
GRANT ALL PRIVILEGES ON `admin`.* TO 'admin'@'%';
/*root用户，管理员*/

REATE USER 'student'@'%' IDENTIFIED WITH mysql_native_password AS '***';GRANT SELECT ON *.* TO 'student'@'%',
      REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `student`;GRANT ALL PRIVILEGES ON `student`.* TO 'student'@'%';
/*student学生表*/

CREATE USER 'teacher'@'%' IDENTIFIED WITH mysql_native_password AS '***';
GRANT SELECT, INSERT, UPDATE, DELETE, FILE, EXECUTE ON *.* TO 'teacher'@'%' ,
REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `teacher`;
GRANT ALL PRIVILEGES ON `teacher`.* TO 'teacher'@'%';
/*teacher"*/
